### ISSUE TITLE
LinearSnapHelper causes reversal of direction in the scrolling

### ISSUE THREAD

**Issue by adrcotfas** [BeksOmega/looping-layout#38]
* **Device**: all devices
* **OS Version**: 29
* **Project Version**: 0.3.1

### :bug: Describe

When attaching a `LinearSnapHelper` to the `RecyclerView`, the scroll misbehaves by unexpected changes in direction. Swiping down will result in a swipe up and vice-versa.
### :snail: Steps to reproduce
Attach a `LinearSnapHelper`
```
val snapHelper = LinearSnapHelper()
snapHelper.attachToRecyclerView(recyclerView)
```
Observe the scolling behavior

### :butterfly: Expected behavior
Normal scrolling behavior

### :bee: Requested assignment
I'm just reporting this problem. I don't want to fix it.

**Comment by adrcotfas** [comment]
My bad for not seeing that there's a `LoopingSnapHelper`.
I'll close this.

**Comment by BeksOmega** [comment]
Thanks for the advice about the Readme that's a good idea! If you still have problems with the LoopingSnapHelper I'm happy to help :D Just be warned I may be a bit slow to respond because I'm a bit swamped with projects atm hehe.

Thank you again! Updating the readme is officially on my todo list =)
